added account apis under user management
LoginRadius/lr-cli pull request #9
Opened 2021-04-09 13:02 UTC by RevanthTanneeru

#### Checklist

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [ ] You created a branch from `develop` branch.
- [ ] You PR is raised on `develop` branch and not on`main`.
- [ ] You have read the [Contribution Guidlines](CONTRIBUTING.md) before creating this PR.

### Description of the Change

### Alternate Designs

### Risk Impact

### Verification Process

### Release Notes

2021-04-10 06:36 UTC, mohammed786 requested changes
Hi @RevanthTanneeru ,
The PR is directly using `api.loginradius.com` instead we will use the admin console api's. Check out the `account-management` microservice for more details.

2021-04-10 06:36 UTC, mohammed786 commented on cmd/add/account/account.go
> +	payload := strings.NewReader("{\n  \"FirstName\":\"" + namestring + "\",\n  \"Email\":[\n    {\n      \"Type\": \"Primary\",\n      \"Value\": \"" + emailstring + "\"\n    }\n  ],\n  \"Password\": \
We already have the `account` struct, can't we use the same and covert it to JSON string?

2021-04-10 06:36 UTC, mohammed786 commented on cmd/add/account/account.go
> +	fmt.Println("Password:" + string(body))
Here we can use the admin console API, instead of login radius API. Check `customer-management` microservice of admin console.

2021-04-10 06:36 UTC, mohammed786 commented on cmd/delete/account/account.go
> +	defer res.Body.Close()
Here we can use the admin console API, instead of login radius API. Check customer-management microservice of admin console.

2021-04-12 12:06 UTC, ravitejag commented on cmd/add/account/account.go
> +	fmt.Println("Your account is successfully created")
@RevanthTanneeru Better to use something like `User Account is successfully created`
cc @mohammed786

2021-04-12 12:07 UTC, ravitejag commented on cmd/add/account/account.go
> +	fmt.Println("Password:" + string(body))
No need to print the actual password
cc @mohammed786

2021-04-12 12:13 UTC, mohammed786 commented on cmd/add/account/account.go
> +	url := "https://api.loginradius.com/identity/v2/manage/account?apikey=" + res1.Key + "&apisecret=" + res1.Secret
use `config.go` `LoginRadiusAPIDomain` vairable

2021-04-13 07:52 UTC, mohammed786 requested changes
Kindly check the below comments and also update review it from your end before adding the changes.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/delete/delete.go
> +	cmd.AddCommand(account_uidCmd)
Can't we use the same account command for both uid and email??
Something like
```
lr delete account --email // should delete account with given email
lr delete account --uid // should delete account with given uid
```
No need for separate cmd.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/account_password/account_password.go
> +package account_password
The package name should be `accountPassword` and similarly, the file name should be `accountPassword.go` as we are following the camelcase for folder structure.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/account_password/account_password.go
> +				return &cmdutil.FlagError{Err: errors.New("`email` is required argument")}
The message should be `uid is required argument`

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/account_password/account_password.go
> +var fileName string
We can remove this if we are not using this.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/account_password/account_password.go
> +	var UIDstring = UID
`UID` is already a string no need to again assign it to a variable, we can directly use that.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/account_password/account_password.go
> +	fmt.Println("password hash is:" + resultResp.PasswordHash)
Here the message should be 
`Password Hash for the <<uid>> is : <<passwordhash>>`

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/profiles/profiles.go
> +	var emailstring = inpEmail
`inpEmail` is already a string we can use it directly

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/profiles/profiles.go
> +	url := config.GetInstance().LoginRadiusAPIDomain + "/identity/v2/manage/account?apikey=" + resObj.Key + "&apisecret=" + resObj.Secret + "&email=" + emailstring
For profiles there must be some other URL right `/identity/v2/manage/account` this endpoint fetches the accounts.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/get/profiles/profiles.go
> +	url := config.GetInstance().LoginRadiusAPIDomain + "/identity/v2/manage/account/" + uidstring + "?apikey=" + resObj.Key + "&apisecret=" + resObj.Secret
For profiles, there must be some other URL.
`/identity/v2/manage/account` - this endpoint fetches the accounts.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/set/account_password/account_password.go
> +package account_password
Change the package name and file name to `accountPassword` instead of `account_password`

2021-04-13 07:52 UTC, mohammed786 commented on cmd/set/account_password/account_password.go
> +var fileName string
You can get rid of this variable.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/set/account_password/account_password.go
> +				return &cmdutil.FlagError{Err: errors.New("`email` is required argument")}
Here the message should be `uid is required argument`

2021-04-13 07:52 UTC, mohammed786 commented on cmd/set/account_password/account_password.go
> +		Example: heredoc.Doc(`$ lr set account_password --inpUID <inpUID> --inpPassword <inpPassword>`),
Seems like the example is wrong. please try it from your end once and then add it here.

2021-04-13 07:52 UTC, mohammed786 commented on cmd/set/account_password/account_password.go
> +	fl.StringVarP(&inpUID, "UID", "u", "", "UID")
flag should always be in small letters `UID` should be `uid`

2021-04-13 07:52 UTC, mohammed786 commented on cmd/set/account_password/account_password.go
> +	var UIDstring = UID
No need to assign it here.

2021-04-13 11:34 UTC, mohammed786 requested changes

2021-04-13 11:34 UTC, mohammed786 commented on cmd/add/account/account.go
> +var fileName string
Please do the cleanup, remove extra variables.

2021-04-13 11:34 UTC, mohammed786 commented on cmd/delete/account/account.go
> +	fmt.Println("User account sucessfully deleted")
As discussed we can show the records deleted right?

2021-04-13 11:34 UTC, mohammed786 commented on cmd/delete/account/account.go
> +	}
Instead of repeating this in the same file, we can create one local function and use it right?

2021-04-13 11:34 UTC, mohammed786 commented on cmd/delete/account/account.go
> +	url := config.GetInstance().LoginRadiusAPIDomain + "/identity/v2/manage/account/" + uidstring + "?apikey=87bbd6b7-f3e7-4dae-95d0-9c8cf72465dc&apisecret=21f67466-43af-493e-b5e4-6be8ccd5beac"
Why we are taking constant api key and secret in this URL?

2021-04-13 11:34 UTC, mohammed786 commented on cmd/delete/account_uid/account_uid.go
> +}
this file is not needed now right?

2021-04-13 16:43 UTC, mohammed786 reviewed
Kindly check the comment and update the code.

2021-04-13 16:43 UTC, mohammed786 commented on cmd/delete/account/account.go
> +			return deletebyEmail(inpEmail)
Why we are putting `email` as a default case? We can use `else if` case instead
```
if inpEmail == "" && inpUID != "" {
	return deletebyUID(inpUID)
} else if inpUID == "" && inpEmail != "" {
	return deletebyEmail(inpEmail)
} else {
	return &cmdutil.FlagError{Err: errors.New("atleast one of the flags is necessary")}
}
```

2021-04-13 16:43 UTC, mohammed786 commented on cmd/delete/account/account.go
> +	resObj, _ := getresObj()
Need to add Error handling here also right, what if the `getresObj()` returns the error?

2021-04-14 05:40 UTC, mohammed786 approved these changes
Look Good

2021-04-14 05:41 UTC, merged